In [7]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
digits=load_digits()

In [9]:
from sklearn.model_selection import cross_val_score

#by using logistic regression

cross_val_score(LogisticRegression(),digits.data,digits.target,cv=3)

C:\ProgramData\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\ProgramData\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

array([0.92153589, 0.94156928, 0.91652755])

In [10]:
#by using svm
cross_val_score(SVC(),digits.data,digits.target,cv=3)

array([0.96494157, 0.97996661, 0.96494157])

In [12]:
#by using randomforestclassifier
cross_val_score(RandomForestClassifier(n_estimators=10),digits.data,digits.target,cv=3)

array([0.89482471, 0.90651085, 0.88647746])

In [13]:
#Parameter tunning using k fold cross validation

scores1 = cross_val_score(RandomForestClassifier(n_estimators=5),digits.data, digits.target, cv=10)
np.average(scores1)

0.8709000620732464

In [14]:
scores2 = cross_val_score(RandomForestClassifier(n_estimators=20),digits.data, digits.target, cv=10)
np.average(scores2)

0.9376753569211669

In [15]:
scores3 = cross_val_score(RandomForestClassifier(n_estimators=35),digits.data, digits.target, cv=10)
np.average(scores3)

0.9460117939168218

In [18]:
scores4 = cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target, cv=10)
np.average(scores4)

0.944891371818746

In [24]:
scores5 = cross_val_score(RandomForestClassifier(n_estimators=60),digits.data, digits.target, cv=10)
np.average(scores5)

0.9515735567970204

In [ ]:
#here it is clearified that random forest classifier is best one at 60 trees
